### PR TITLE
chore: tag packages with shared/core/plugin/tooling and set dep constraints

### LINKED ISSUE #28: Nx project tags and lint rule setup
- [x] define system for tagging Nx projects
- [x] automate boundary checks using `@nx/enforce-module-boundaries` lint rule options

### PR DESCRIPTION
**Pull request by matejchalk**
Closes #28 

Inspired by discussion in #75 

## Nx tags and project graph (updated)

image

[Excalidraw link](https://excalidraw.com/#json=G4yPscrHmeVyCQEMCJiUW,WqpNLsWLXQLk6E_iRPKnPQ)

### CODE REVIEW

**Comment by ChristopherPHolder** [comment]
Why are you creating a "shared" tag? 

Isn't "utils" and "models" already a common way to structure a project? 

I also don't think the CLI should be importing from "utils".  Doing this means that the cli depends directly on the implementations in utils. 

Currently it is only importing a couple of things which probably should be in core. 

For example `importModule` , will this be used by a plugin? Or is this part of the core functionality? 

Same with `logErrorBeforeThrow` and with `CollectOptions`

**Comment by matejchalk** [comment]
> Why are you creating a "shared" tag?
> 
> Isn't "utils" and "models" already a common way to structure a project?
> 
> I also don't think the CLI should be importing from "utils". Doing this means that the cli depends directly on the implementations in utils.
> 
> Currently it is only importing a couple of things which probably should be in core.
> 
> For example `importModule` , will this be used by a plugin? Or is this part of the core functionality?
> 
> Same with `logErrorBeforeThrow` and with `CollectOptions`

My thinking was to separate `core` and `plugin` scopes, so everything that's available to both is `shared`.

What you're suggesting would require even more granularity in the tags. Basically, every package would need to have it's own dedicated tag, except for plugins.

In other words, instead of:

|package|tag|
|:--|:--|
|cli|core|
|core|core|
|utils|shared|
|models|shared|
|plugin-eslint|plugin|
|plugin-lighthouse|plugin|
|nx-plugin|tooling|

we would have:

|package|tag|
|:--|:--|
|cli|cli|
|core|core|
|utils|utils|
|models|models|
|plugin-eslint|plugin|
|plugin-lighthouse|plugin|
|nx-plugin|nx-plugin|

I originally wanted to avoid having many unique tags. I've previously thought of tags as a way to group projects by different dimensions (`scope` and `type`, usually), but maybe that only makes sense for applications. So if you think it's better to have single-purpose tags, then I can do it this way.

**Review by ChristopherPHolder — APPROVED** [review]

**Comment by matejchalk** [comment]
Yeah, it's quite possible we will be wiser about the project boundaries later on, so I'm all for going with a simple version for now and extending it later once it's clearer what we need.

Adding it to the project README is a good idea :+1: I'm happy to do that in this PR, or in a follow-up if you prefer (it's about time we replaced the generated Nx README anyway).

I really the Greenforce monorepo example you shared, though :slightly_smiling_face:  I've used the same 2D tags system suggested by Nx for several application monorepos ([the portal also uses it](https://github.com/flowup/quality-metrics-portal/blob/main/.eslintrc.json#L81-L164)), and this has even more types of libraries that could be useful. Unfortunately, I don't think a lot of them apply for this repo, which is a lot smaller and simpler.

But it got me thinking if we couldn't apply some of it after all :thinking: I would consider the tags I introduced to be `scope` tags, so we maybe could introduce the `type` tag dimension as well. Specifically, I think `type:shell`, `type:feature` and `type:util` (maybe also `type:test-util` or even `type:e2e-util` in the future) could apply for us:

|project|scope|type|
|:--|:--|:--|
|cli|core|shell|
|core|core|feature|
|utils|shared|util|
|models|shared|util|
|plugin-eslint|plugin|feature|
|plugin-lighthouse|plugin|feature|
|nx-plugin|tooling|shell|

What do you think?

**Comment by ChristopherPHolder** [comment]
# This is not finished, will finish and pin you 


### Applications

| Type | Contains | Allow Dependencies |
| --- | --- | --- |
| `app` |  Entry point for the executable |  `shell`  | 
| `app-e2e | Runs E2E tests on the executable | `e2e-utils` |

### Library types

| Type | Contains | Allow Dependencies |
| --- | --- | --- |
| `shell` | Entrypoint for an application or domain. Orchestration and routing. | `util` `feature` |
| `util` | Low-level utilities used by many libraries and applications (services, pure functions, contants). | `util` |
| `feature` | TODO | `domain` `util` | 


Again here i am making the distinction that the cli is an application not a library. 

By defining the `Allowed Dependencies` are specifying the scope.


The result would be this: 

| Project | Type |  
| --- | --- | 
| cli | app |
| core | |
| utils | |
| models | | 
| plugin-eslint |  |
| plugin-lighthouse |  |
| nx-plugin |  |

**Review by ChristopherPHolder — APPROVED** [review]

**Comment by matejchalk** [comment]
@ChristopherPHolder OK, I've made some changes based on what makes sense at this time. I recommended taking a look at the updated PR description.

I introduced the 2D tagging, although I just went with types `app`, `feature`, `util` and `e2e`.

I didn't go with `domain` because I don't think that distinction is useful here as we only have one "domain". And it would constrain us from importing types from `models` into `utils`. We have quite a few of those imports (e.g. we have report formatting logic in `utils` which needs the `Report` type), and I'm not sure refactoring it would be worthwhile (not much would be left in `utils` after that).

I agree with `cli` being more of an application than a library, especially now that we want the entry point to be executable. I changed the Nx project type as well to reflect it. But since this now makes it a `type:app`, I didn't see much value in having `type:shell`, so I just went with `type:feature`, same as for plugins.

**Review by ChristopherPHolder — APPROVED** [review]

**Pull request merged**
