### PR TITLE
refactor(cli): add entry point for bin

### PR DESCRIPTION
**Pull request by ChristopherPHolder**
This MR addresses the issue from MR #49

image

### CODE REVIEW

**Comment by BioPhoton** [comment]
@ChristopherPHolder thx for having a look at this!

Did you try to execute the build artefact?
`npx dist/packages/cli collect`

**Review by BioPhoton — CHANGES_REQUESTED** [review]
Would a combination of bundle false + the additional entry point work for us?

**Comment by ChristopherPHolder** [comment]
> Would a combination of bundle false + the additional entry point work for us?

It is worth testing it.

**Comment by matejchalk** [comment]
I had to change the `bin.js` path, but otherwise this seems to work just fine :slightly_smiling_face: 

image

**Comment by BioPhoton** [comment]
Here another 🧩 of the puzzle:
https://github.com/favware/esbuild-plugin-file-path-extensions

**Comment by ChristopherPHolder** [comment]
So it seems it is really not straight forward. Just to getting running for the moment i have converted the bin to a .js file and passed as an asset. 

I know this is not optimal and i am looking into the configuration for getting the bundling correct without the issue of import file extensions.

**Comment by ChristopherPHolder** [comment]
Relevent: https://github.com/evanw/esbuild/issues/622

**Comment by matejchalk** [comment]
I'm OK with the `bin.js` asset as a workaround :man_shrugging: 

Although as mentioned in #73, maybe we don't need two entry points for the `cli` anyway, `index.ts` could just execute instead of only exporting a function. I'm not sure we need to support importing from `cli`, users that want programmatic usage should be able to import everything they need from `core` (or `models`, `utils`, etc.).

**Comment by BioPhoton** [comment]
I'm in for the core package!
lets for now have only the `bin.ts` file present and merge the discussed approach for the cli package.
I'll setup a core package later.

**Comment by BioPhoton** [comment]
closed as implemented in #66

**Pull request closed without merging**
